/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CashFlowCashFlowBalance;
import com.konfigthis.client.model.CashFlowCashFlowCharacteristic;
import com.konfigthis.client.model.CashFlowCashFlowCredit;
import com.konfigthis.client.model.CashFlowCashFlowDebit;
import com.konfigthis.client.model.ReportTransaction;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CashFlowReportAccount
 */
public class CashFlowReportAccountTest {
    private final CashFlowReportAccount model = new CashFlowReportAccount();

    /**
     * Model tests for CashFlowReportAccount
     */
    @Test
    public void testCashFlowReportAccount() {
        // TODO: test CashFlowReportAccount
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'ownerName'
     */
    @Test
    public void ownerNameTest() {
        // TODO: test ownerName
    }

    /**
     * Test the property 'ownerAddress'
     */
    @Test
    public void ownerAddressTest() {
        // TODO: test ownerAddress
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'aggregationStatusCode'
     */
    @Test
    public void aggregationStatusCodeTest() {
        // TODO: test aggregationStatusCode
    }

    /**
     * Test the property 'currentBalance'
     */
    @Test
    public void currentBalanceTest() {
        // TODO: test currentBalance
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'balanceDate'
     */
    @Test
    public void balanceDateTest() {
        // TODO: test balanceDate
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

    /**
     * Test the property 'cashFlowBalance'
     */
    @Test
    public void cashFlowBalanceTest() {
        // TODO: test cashFlowBalance
    }

    /**
     * Test the property 'cashFlowCredit'
     */
    @Test
    public void cashFlowCreditTest() {
        // TODO: test cashFlowCredit
    }

    /**
     * Test the property 'cashFlowDebit'
     */
    @Test
    public void cashFlowDebitTest() {
        // TODO: test cashFlowDebit
    }

    /**
     * Test the property 'cashFlowCharacteristic'
     */
    @Test
    public void cashFlowCharacteristicTest() {
        // TODO: test cashFlowCharacteristic
    }

}
