/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CashFlowMonthlyCashFlowCredits;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CashFlowCashFlowCredit
 */
public class CashFlowCashFlowCreditTest {
    private final CashFlowCashFlowCredit model = new CashFlowCashFlowCredit();

    /**
     * Model tests for CashFlowCashFlowCredit
     */
    @Test
    public void testCashFlowCashFlowCredit() {
        // TODO: test CashFlowCashFlowCredit
    }

    /**
     * Test the property 'monthlyCashFlowCredits'
     */
    @Test
    public void monthlyCashFlowCreditsTest() {
        // TODO: test monthlyCashFlowCredits
    }

    /**
     * Test the property 'twelveMonthCreditTotal'
     */
    @Test
    public void twelveMonthCreditTotalTest() {
        // TODO: test twelveMonthCreditTotal
    }

    /**
     * Test the property 'twelveMonthCreditTotalLessTransfers'
     */
    @Test
    public void twelveMonthCreditTotalLessTransfersTest() {
        // TODO: test twelveMonthCreditTotalLessTransfers
    }

    /**
     * Test the property 'sixMonthCreditTotal'
     */
    @Test
    public void sixMonthCreditTotalTest() {
        // TODO: test sixMonthCreditTotal
    }

    /**
     * Test the property 'sixMonthCreditTotalLessTransfers'
     */
    @Test
    public void sixMonthCreditTotalLessTransfersTest() {
        // TODO: test sixMonthCreditTotalLessTransfers
    }

    /**
     * Test the property 'twoMonthCreditTotal'
     */
    @Test
    public void twoMonthCreditTotalTest() {
        // TODO: test twoMonthCreditTotal
    }

    /**
     * Test the property 'twoMonthCreditTotalLessTransfers'
     */
    @Test
    public void twoMonthCreditTotalLessTransfersTest() {
        // TODO: test twoMonthCreditTotalLessTransfers
    }

}
