/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Transaction;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Transactions
 */
public class TransactionsTest {
    private final Transactions model = new Transactions();

    /**
     * Model tests for Transactions
     */
    @Test
    public void testTransactions() {
        // TODO: test Transactions
    }

    /**
     * Test the property 'found'
     */
    @Test
    public void foundTest() {
        // TODO: test found
    }

    /**
     * Test the property 'displaying'
     */
    @Test
    public void displayingTest() {
        // TODO: test displaying
    }

    /**
     * Test the property 'moreAvailable'
     */
    @Test
    public void moreAvailableTest() {
        // TODO: test moreAvailable
    }

    /**
     * Test the property 'fromDate'
     */
    @Test
    public void fromDateTest() {
        // TODO: test fromDate
    }

    /**
     * Test the property 'toDate'
     */
    @Test
    public void toDateTest() {
        // TODO: test toDate
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

}
