/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CashFlowMonthlyCashFlowBalanceSummaries
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CashFlowMonthlyCashFlowBalanceSummaries {
  public static final String SERIALIZED_NAME_MONTH = "month";
  @SerializedName(SERIALIZED_NAME_MONTH)
  private Long month;

  public static final String SERIALIZED_NAME_MIN_DAILY_BALANCE = "minDailyBalance";
  @SerializedName(SERIALIZED_NAME_MIN_DAILY_BALANCE)
  private Double minDailyBalance;

  public static final String SERIALIZED_NAME_MAX_DAILY_BALANCE = "maxDailyBalance";
  @SerializedName(SERIALIZED_NAME_MAX_DAILY_BALANCE)
  private Double maxDailyBalance;

  public static final String SERIALIZED_NAME_AVERAGE_DAILY_BALANCE = "averageDailyBalance";
  @SerializedName(SERIALIZED_NAME_AVERAGE_DAILY_BALANCE)
  private Double averageDailyBalance;

  public static final String SERIALIZED_NAME_STANDARD_DEVIATION_OF_DAILY_BALANCE = "standardDeviationOfDailyBalance";
  @SerializedName(SERIALIZED_NAME_STANDARD_DEVIATION_OF_DAILY_BALANCE)
  private String standardDeviationOfDailyBalance;

  public static final String SERIALIZED_NAME_NUMBER_OF_DAYS_NEGATIVE_BALANCE = "numberOfDaysNegativeBalance";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_DAYS_NEGATIVE_BALANCE)
  private String numberOfDaysNegativeBalance;

  public static final String SERIALIZED_NAME_NUMBER_OF_DAYS_POSITIVE_BALANCE = "numberOfDaysPositiveBalance";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_DAYS_POSITIVE_BALANCE)
  private String numberOfDaysPositiveBalance;

  public CashFlowMonthlyCashFlowBalanceSummaries() {
  }

  public CashFlowMonthlyCashFlowBalanceSummaries month(Long month) {
    
    
    
    
    this.month = month;
    return this;
  }

   /**
   * One instance for each complete calendar month in the report
   * @return month
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1512111600", required = true, value = "One instance for each complete calendar month in the report")

  public Long getMonth() {
    return month;
  }


  public void setMonth(Long month) {
    
    
    
    this.month = month;
  }


  public CashFlowMonthlyCashFlowBalanceSummaries minDailyBalance(Double minDailyBalance) {
    
    
    
    
    this.minDailyBalance = minDailyBalance;
    return this;
  }

  public CashFlowMonthlyCashFlowBalanceSummaries minDailyBalance(Integer minDailyBalance) {
    
    
    
    
    this.minDailyBalance = minDailyBalance.doubleValue();
    return this;
  }

   /**
   * Min Daily Balance for each month for all accounts
   * @return minDailyBalance
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "3479.39", required = true, value = "Min Daily Balance for each month for all accounts")

  public Double getMinDailyBalance() {
    return minDailyBalance;
  }


  public void setMinDailyBalance(Double minDailyBalance) {
    
    
    
    this.minDailyBalance = minDailyBalance;
  }


  public CashFlowMonthlyCashFlowBalanceSummaries maxDailyBalance(Double maxDailyBalance) {
    
    
    
    
    this.maxDailyBalance = maxDailyBalance;
    return this;
  }

  public CashFlowMonthlyCashFlowBalanceSummaries maxDailyBalance(Integer maxDailyBalance) {
    
    
    
    
    this.maxDailyBalance = maxDailyBalance.doubleValue();
    return this;
  }

   /**
   * Max Daily Balance for each month for all accounts
   * @return maxDailyBalance
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "3479.39", required = true, value = "Max Daily Balance for each month for all accounts")

  public Double getMaxDailyBalance() {
    return maxDailyBalance;
  }


  public void setMaxDailyBalance(Double maxDailyBalance) {
    
    
    
    this.maxDailyBalance = maxDailyBalance;
  }


  public CashFlowMonthlyCashFlowBalanceSummaries averageDailyBalance(Double averageDailyBalance) {
    
    
    
    
    this.averageDailyBalance = averageDailyBalance;
    return this;
  }

  public CashFlowMonthlyCashFlowBalanceSummaries averageDailyBalance(Integer averageDailyBalance) {
    
    
    
    
    this.averageDailyBalance = averageDailyBalance.doubleValue();
    return this;
  }

   /**
   * Average Daily Balance for each month for all accounts
   * @return averageDailyBalance
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "3479.39", required = true, value = "Average Daily Balance for each month for all accounts")

  public Double getAverageDailyBalance() {
    return averageDailyBalance;
  }


  public void setAverageDailyBalance(Double averageDailyBalance) {
    
    
    
    this.averageDailyBalance = averageDailyBalance;
  }


  public CashFlowMonthlyCashFlowBalanceSummaries standardDeviationOfDailyBalance(String standardDeviationOfDailyBalance) {
    
    
    
    
    this.standardDeviationOfDailyBalance = standardDeviationOfDailyBalance;
    return this;
  }

   /**
   * Standard Deviation of Daily Balance for each month for all accounts
   * @return standardDeviationOfDailyBalance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "20.45454545", value = "Standard Deviation of Daily Balance for each month for all accounts")

  public String getStandardDeviationOfDailyBalance() {
    return standardDeviationOfDailyBalance;
  }


  public void setStandardDeviationOfDailyBalance(String standardDeviationOfDailyBalance) {
    
    
    
    this.standardDeviationOfDailyBalance = standardDeviationOfDailyBalance;
  }


  public CashFlowMonthlyCashFlowBalanceSummaries numberOfDaysNegativeBalance(String numberOfDaysNegativeBalance) {
    
    
    
    
    this.numberOfDaysNegativeBalance = numberOfDaysNegativeBalance;
    return this;
  }

   /**
   * Number of Days Negative Balance for each month for all accounts
   * @return numberOfDaysNegativeBalance
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "6", required = true, value = "Number of Days Negative Balance for each month for all accounts")

  public String getNumberOfDaysNegativeBalance() {
    return numberOfDaysNegativeBalance;
  }


  public void setNumberOfDaysNegativeBalance(String numberOfDaysNegativeBalance) {
    
    
    
    this.numberOfDaysNegativeBalance = numberOfDaysNegativeBalance;
  }


  public CashFlowMonthlyCashFlowBalanceSummaries numberOfDaysPositiveBalance(String numberOfDaysPositiveBalance) {
    
    
    
    
    this.numberOfDaysPositiveBalance = numberOfDaysPositiveBalance;
    return this;
  }

   /**
   * Number of Days Positive Balance for each month for all accounts
   * @return numberOfDaysPositiveBalance
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "0", required = true, value = "Number of Days Positive Balance for each month for all accounts")

  public String getNumberOfDaysPositiveBalance() {
    return numberOfDaysPositiveBalance;
  }


  public void setNumberOfDaysPositiveBalance(String numberOfDaysPositiveBalance) {
    
    
    
    this.numberOfDaysPositiveBalance = numberOfDaysPositiveBalance;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CashFlowMonthlyCashFlowBalanceSummaries instance itself
   */
  public CashFlowMonthlyCashFlowBalanceSummaries putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashFlowMonthlyCashFlowBalanceSummaries cashFlowMonthlyCashFlowBalanceSummaries = (CashFlowMonthlyCashFlowBalanceSummaries) o;
    return Objects.equals(this.month, cashFlowMonthlyCashFlowBalanceSummaries.month) &&
        Objects.equals(this.minDailyBalance, cashFlowMonthlyCashFlowBalanceSummaries.minDailyBalance) &&
        Objects.equals(this.maxDailyBalance, cashFlowMonthlyCashFlowBalanceSummaries.maxDailyBalance) &&
        Objects.equals(this.averageDailyBalance, cashFlowMonthlyCashFlowBalanceSummaries.averageDailyBalance) &&
        Objects.equals(this.standardDeviationOfDailyBalance, cashFlowMonthlyCashFlowBalanceSummaries.standardDeviationOfDailyBalance) &&
        Objects.equals(this.numberOfDaysNegativeBalance, cashFlowMonthlyCashFlowBalanceSummaries.numberOfDaysNegativeBalance) &&
        Objects.equals(this.numberOfDaysPositiveBalance, cashFlowMonthlyCashFlowBalanceSummaries.numberOfDaysPositiveBalance)&&
        Objects.equals(this.additionalProperties, cashFlowMonthlyCashFlowBalanceSummaries.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(month, minDailyBalance, maxDailyBalance, averageDailyBalance, standardDeviationOfDailyBalance, numberOfDaysNegativeBalance, numberOfDaysPositiveBalance, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CashFlowMonthlyCashFlowBalanceSummaries {\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    minDailyBalance: ").append(toIndentedString(minDailyBalance)).append("\n");
    sb.append("    maxDailyBalance: ").append(toIndentedString(maxDailyBalance)).append("\n");
    sb.append("    averageDailyBalance: ").append(toIndentedString(averageDailyBalance)).append("\n");
    sb.append("    standardDeviationOfDailyBalance: ").append(toIndentedString(standardDeviationOfDailyBalance)).append("\n");
    sb.append("    numberOfDaysNegativeBalance: ").append(toIndentedString(numberOfDaysNegativeBalance)).append("\n");
    sb.append("    numberOfDaysPositiveBalance: ").append(toIndentedString(numberOfDaysPositiveBalance)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("month");
    openapiFields.add("minDailyBalance");
    openapiFields.add("maxDailyBalance");
    openapiFields.add("averageDailyBalance");
    openapiFields.add("standardDeviationOfDailyBalance");
    openapiFields.add("numberOfDaysNegativeBalance");
    openapiFields.add("numberOfDaysPositiveBalance");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("month");
    openapiRequiredFields.add("minDailyBalance");
    openapiRequiredFields.add("maxDailyBalance");
    openapiRequiredFields.add("averageDailyBalance");
    openapiRequiredFields.add("numberOfDaysNegativeBalance");
    openapiRequiredFields.add("numberOfDaysPositiveBalance");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CashFlowMonthlyCashFlowBalanceSummaries
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CashFlowMonthlyCashFlowBalanceSummaries.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CashFlowMonthlyCashFlowBalanceSummaries is not found in the empty JSON string", CashFlowMonthlyCashFlowBalanceSummaries.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CashFlowMonthlyCashFlowBalanceSummaries.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("standardDeviationOfDailyBalance") != null && !jsonObj.get("standardDeviationOfDailyBalance").isJsonNull()) && !jsonObj.get("standardDeviationOfDailyBalance").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `standardDeviationOfDailyBalance` to be a primitive type in the JSON string but got `%s`", jsonObj.get("standardDeviationOfDailyBalance").toString()));
      }
      if (!jsonObj.get("numberOfDaysNegativeBalance").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `numberOfDaysNegativeBalance` to be a primitive type in the JSON string but got `%s`", jsonObj.get("numberOfDaysNegativeBalance").toString()));
      }
      if (!jsonObj.get("numberOfDaysPositiveBalance").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `numberOfDaysPositiveBalance` to be a primitive type in the JSON string but got `%s`", jsonObj.get("numberOfDaysPositiveBalance").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CashFlowMonthlyCashFlowBalanceSummaries.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CashFlowMonthlyCashFlowBalanceSummaries' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CashFlowMonthlyCashFlowBalanceSummaries> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CashFlowMonthlyCashFlowBalanceSummaries.class));

       return (TypeAdapter<T>) new TypeAdapter<CashFlowMonthlyCashFlowBalanceSummaries>() {
           @Override
           public void write(JsonWriter out, CashFlowMonthlyCashFlowBalanceSummaries value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CashFlowMonthlyCashFlowBalanceSummaries read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CashFlowMonthlyCashFlowBalanceSummaries instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CashFlowMonthlyCashFlowBalanceSummaries given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CashFlowMonthlyCashFlowBalanceSummaries
  * @throws IOException if the JSON string is invalid with respect to CashFlowMonthlyCashFlowBalanceSummaries
  */
  public static CashFlowMonthlyCashFlowBalanceSummaries fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CashFlowMonthlyCashFlowBalanceSummaries.class);
  }

 /**
  * Convert an instance of CashFlowMonthlyCashFlowBalanceSummaries to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

