/*
 * Open Banking
 * OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DirectDeposits
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DirectDeposits {
  public static final String SERIALIZED_NAME_ACCOUNT_TYPE_CODE = "accountTypeCode";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_TYPE_CODE)
  private String accountTypeCode;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private Double amount;

  public static final String SERIALIZED_NAME_ACCOUNT_LAST_FOUR = "accountLastFour";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_LAST_FOUR)
  private String accountLastFour;

  public static final String SERIALIZED_NAME_ROUTING_NUMBER = "routingNumber";
  @SerializedName(SERIALIZED_NAME_ROUTING_NUMBER)
  private String routingNumber;

  public DirectDeposits() {
  }

  public DirectDeposits accountTypeCode(String accountTypeCode) {
    
    
    
    
    this.accountTypeCode = accountTypeCode;
    return this;
  }

   /**
   * Bank account type:  * &#x60;Checking&#x60;  * &#x60;Savings&#x60;  * &#x60;Loan&#x60;: Loan account employee choose to direct a portion of their net pay to help pay off a loan 
   * @return accountTypeCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Savings", value = "Bank account type:  * `Checking`  * `Savings`  * `Loan`: Loan account employee choose to direct a portion of their net pay to help pay off a loan ")

  public String getAccountTypeCode() {
    return accountTypeCode;
  }


  public void setAccountTypeCode(String accountTypeCode) {
    
    
    
    this.accountTypeCode = accountTypeCode;
  }


  public DirectDeposits amount(Double amount) {
    
    
    
    
    this.amount = amount;
    return this;
  }

  public DirectDeposits amount(Integer amount) {
    
    
    
    
    this.amount = amount.doubleValue();
    return this;
  }

   /**
   * Direct deposit amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12.34", value = "Direct deposit amount")

  public Double getAmount() {
    return amount;
  }


  public void setAmount(Double amount) {
    
    
    
    this.amount = amount;
  }


  public DirectDeposits accountLastFour(String accountLastFour) {
    
    
    
    
    this.accountLastFour = accountLastFour;
    return this;
  }

   /**
   * Last four digits of the deposit account number
   * @return accountLastFour
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3337", value = "Last four digits of the deposit account number")

  public String getAccountLastFour() {
    return accountLastFour;
  }


  public void setAccountLastFour(String accountLastFour) {
    
    
    
    this.accountLastFour = accountLastFour;
  }


  public DirectDeposits routingNumber(String routingNumber) {
    
    
    
    
    this.routingNumber = routingNumber;
    return this;
  }

   /**
   * Routing number for the deposit account
   * @return routingNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "30207583", value = "Routing number for the deposit account")

  public String getRoutingNumber() {
    return routingNumber;
  }


  public void setRoutingNumber(String routingNumber) {
    
    
    
    this.routingNumber = routingNumber;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DirectDeposits instance itself
   */
  public DirectDeposits putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DirectDeposits directDeposits = (DirectDeposits) o;
    return Objects.equals(this.accountTypeCode, directDeposits.accountTypeCode) &&
        Objects.equals(this.amount, directDeposits.amount) &&
        Objects.equals(this.accountLastFour, directDeposits.accountLastFour) &&
        Objects.equals(this.routingNumber, directDeposits.routingNumber)&&
        Objects.equals(this.additionalProperties, directDeposits.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountTypeCode, amount, accountLastFour, routingNumber, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DirectDeposits {\n");
    sb.append("    accountTypeCode: ").append(toIndentedString(accountTypeCode)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    accountLastFour: ").append(toIndentedString(accountLastFour)).append("\n");
    sb.append("    routingNumber: ").append(toIndentedString(routingNumber)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accountTypeCode");
    openapiFields.add("amount");
    openapiFields.add("accountLastFour");
    openapiFields.add("routingNumber");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DirectDeposits
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DirectDeposits.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DirectDeposits is not found in the empty JSON string", DirectDeposits.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("accountTypeCode") != null && !jsonObj.get("accountTypeCode").isJsonNull()) && !jsonObj.get("accountTypeCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accountTypeCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountTypeCode").toString()));
      }
      if ((jsonObj.get("accountLastFour") != null && !jsonObj.get("accountLastFour").isJsonNull()) && !jsonObj.get("accountLastFour").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accountLastFour` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountLastFour").toString()));
      }
      if ((jsonObj.get("routingNumber") != null && !jsonObj.get("routingNumber").isJsonNull()) && !jsonObj.get("routingNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `routingNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("routingNumber").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DirectDeposits.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DirectDeposits' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DirectDeposits> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DirectDeposits.class));

       return (TypeAdapter<T>) new TypeAdapter<DirectDeposits>() {
           @Override
           public void write(JsonWriter out, DirectDeposits value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DirectDeposits read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DirectDeposits instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DirectDeposits given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DirectDeposits
  * @throws IOException if the JSON string is invalid with respect to DirectDeposits
  */
  public static DirectDeposits fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DirectDeposits.class);
  }

 /**
  * Convert an instance of DirectDeposits to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

